import subprocess
import shlex
import logging
from pathlib import Path
import pty
import os
import errno
import select
from typing import Any

from common_defs import abort_with_message
from compilation import get_binary_path


LOGGER = logging.getLogger(__name__)


def _run_test_binary(command: list[str], show_online: bool) -> tuple[str, int | Any]:
    # WARNING: the code was generated by Google AI agent

    # Create a master and a slave file descriptor for the pseudo-terminal
    master_fd, slave_fd = pty.openpty()

    # Start the subprocess with its stdout and stderr connected to the slave
    # The stdin could also be connected to the slave for interactive input
    process = subprocess.Popen(
        command,
        stdout=slave_fd,
        stderr=slave_fd,  # Merges stderr into stdout stream
        stdin=slave_fd,
        bufsize=0  # Unbuffered I/O
    )

    # Close the slave file descriptor in the parent process
    os.close(slave_fd)

    output = []
    # Use select to wait for data to be available on the master file descriptor
    while True:
        try:
            # Check if the process has terminated
            if process.poll() is not None:
                break
            
            # Use select to check if data is available to read from the master
            if select.select([master_fd], [], [], 0.01)[0]:
                data = os.read(master_fd, 1024)
                if not data:
                    break
                current_output = data.decode('utf-8')
                if show_online:
                    print(current_output, end='')
                output.append(current_output)
        except OSError as e:
            # Handle potential EIO errors that can occur when the slave end is closed
            if e.errno == errno.EIO:
                break
            raise
    
    # Wait for the process to fully terminate
    process.wait()
    
    # Close the master file descriptor
    os.close(master_fd)

    return "".join(output), process.returncode


def _get_tests_result(bin_path: Path, show_online: bool) -> tuple[int, int]:
    args = f"{bin_path}"
    cmd = shlex.split(args)
    test_bin_output, returncode = _run_test_binary(cmd, show_online)
    if returncode:
        if not test_bin_output or "FAILED TESTS:" not in test_bin_output:
            extra_line = ""
            if not show_online:
                extra_line += f".\nFull test output:\n{test_bin_output}"
            abort_with_message(f"Test was failed. Process returned non-zero code {returncode}{extra_line}")
        LOGGER.warning(f"{returncode} tests were failed")
        failed_tests = test_bin_output.split("FAILED TESTS:")[1].strip()
        LOGGER.warning(f"Failed tests: \n{failed_tests}")
    else:
        LOGGER.info("Tests passed")
    total_info = test_bin_output.split("TOTAL")[1]
    passed_count = int(total_info.split("PASSED: ")[1].split('\n')[0])
    failed_count = int(total_info.split("FAILED: ")[1].split('\n')[0])
    return passed_count, failed_count


def full_test(compilation_profiles: list[str], device_name: str, no_recompile: bool, show_online: bool):
    all_passed_count = 0
    all_failed_count = 0
    failed_profiles = set()
    for compilation_profile in compilation_profiles:
        LOGGER.info(f"Current compilation profile: {compilation_profile}")
        bin_path = get_binary_path(compilation_profile, device_name, compilation_type="test", eigen_path=None, no_recompile=no_recompile)
        LOGGER.info("Running tests")
        current_passed_count, current_failed_count = _get_tests_result(bin_path, show_online)
        all_failed_count += current_failed_count
        all_passed_count += current_passed_count
        if current_failed_count:
            failed_profiles.add(compilation_profile)
    LOGGER.info(f"All test count: {all_passed_count + all_failed_count}")
    LOGGER.info(f"Passed test count: {all_passed_count}")
    LOGGER.info(f"Failed test count: {all_failed_count}")
    if all_failed_count:
        failed_profiles_str = "\", \"".join(failed_profiles)
        LOGGER.info(f"Tests were failed in \"{failed_profiles_str}\" profiles")
